version: '3'

services:
  balancer:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    build: .
    image: qaxim/devops-camp:latest
    environment:
      - PORT=5555
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    deploy:
      replicas: 6
      restart_policy:
        condition: any
      update_config:
        parallelism: 3
        delay: 20s
  db:
    image: postgres:13.9-alpine
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "${POSTGRES_USER}" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
  shepherd:
    build: .
    image: mazzolino/shepherd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - IGNORELIST_SERVICES=tasker_shepherd
      - IGNORELIST_SERVICES=tasker_balancer
      - IGNORELIST_SERVICES=tasker_db
      - SLEEP_TIME=2m
    deploy:
      placement:
        constraints:
        - node.role == manager

volumes:
  db-data:
