version: '3'

services:
  balancer:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5555:80"
    depends_on:
      - api
  api:
    build: .
    environment:
      - PORT=5555