version: '3'

services:
  balancer:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "5555:80"
    depends_on:
      - api
  api:
    build: .
    environment:
      - PORT=5555
    volumes:
      - .:/app/src/:ro
    depends_on:
      - db
  db:
    image: postgres:13.9-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: